[package]
name = "rust-bell"
version = "0.1.0"
authors = ["Mik <mik@miklabs.com>"]
edition = "2018"

description = "Live coding music"
license = "MIT/Apache-2.0"
repository = "https://github.com/mikbry/rust-bell"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
